---
- name: Install prerequisites
  apt: name={{ item }}
  with_items:
    - build-essential
    - libgoogle-glog-dev
    - libgflags-dev
    - libeigen3-dev
    - libopencv-dev
    - libcppnetlib-dev
    - libboost-dev
    - libcurlpp-dev
    - libcurl4-openssl-dev
    - protobuf-compiler
    - libopenblas-dev
    - libhdf5-dev
    - libprotobuf-dev
    - libleveldb-dev
    - libsnappy-dev
    - liblmdb-dev
    - git
    - cmake
